config/routes.rb
Rails.application.routes.draw do

  root 'clients#index'
  resources :clients
  resources :sights
  resources :heartrates
  resources :blood_pressures
  resources :logs
  resources :cholesterols
  resources :hba1cs
  resources :glucoses
  resources :medications
  resources :weights
  resources :weight_targets
  resources :hba1c_targets
  resources :blood_pressure_targets
  resources :heartrate_targets
  resources :cholesterol_targets
  resources :glucose_targets
  resources :nutritions
  resources :complaints
  resources :medication_usages
  

end

app/models/activity_type.rb
class ActivityType < ActiveRecord::Base
end

app/models/allergy.rb
class Allergy < ActiveRecord::Base
end

app/models/cholesterol.rb
class Cholesterol < ActiveRecord::Base
end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
end

app/models/disease.rb
class Disease < ActiveRecord::Base
end

app/models/glucose.rb
class Glucose < ActiveRecord::Base
end

app/models/hba1c.rb
class Hba1c < ActiveRecord::Base
end

app/models/hba1c_target.rb
class Hba1cTarget < ActiveRecord::Base
end

app/models/heartrate.rb
class Heartrate < ActiveRecord::Base
end

app/models/institution.rb
class Institution < ActiveRecord::Base
end

app/models/length.rb
class Length < ActiveRecord::Base
end

app/models/log.rb
class Log < ActiveRecord::Base
end

app/models/medication.rb
class Medication < ActiveRecord::Base
end

app/models/nutrition.rb
class Nutrition < ActiveRecord::Base
end

app/models/sight.rb
class Sight < ActiveRecord::Base
end

app/models/weight.rb
class Weight < ActiveRecord::Base
end

app/models/weight_target.rb
class WeightTarget < ActiveRecord::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @glucose = Glucose.all
    @client = Client.all
    @length = Length.all
    @medication = Medication.all
    @weight = Weight.all
    @log = Log.all
    @glucose_target = GlucoseTarget.all
    @sight = Sight.all
  end

  def new
    @client = Client.new
  end

  def edit
    @client = Client.find(params[:id])
  end

  def create
    @client = Client.new client_params
    @client.save
    redirect_to clients_path
  end

  def show
    @complaint = Complaint.new
    @weight = Weight.new
    @weight_target = WeightTarget.new
    @medication = Medication.new
    @glucose = Glucose.new
    @glucose_target = GlucoseTarget.new
    @hba1c = Hba1c.new
    @hba1c_target = Hba1cTarget.new
    @blood_pressure = BloodPressure.new
    @blood_pressure_target = BloodPressureTarget.new
    @heartrate = Heartrate.new
    @heartrate_target = HeartrateTarget.new
    @cholesterol = Cholesterol.new
    @cholesterol_target = CholesterolTarget.new
    @nutrition = Nutrition.new
    @log = Log.new
    @medication_usage = MedicationUsage.new
    @client = Client.find(params[:id])
    @glucoses = Glucose.where(client_id: params[:id]).order('activity_date ASC')
    @hba1c_targets = Hba1cTarget.where(client_id: params[:id])
    @blood_pressure_targets = BloodPressureTarget.where(client_id: params[:id])
    @heartrate_targets = HeartrateTarget.where(client_id: params[:id])
    @cholesterol_targets = CholesterolTarget.where(client_id: params[:id])
    @client_hba1c = Hba1c.where(client_id: params[:id]).order('activity_date DESC').limit(2)
    @heartrates = Heartrate.where(client_id: params[:id]).order('activity_date DESC').limit(2)
    @client_log = Log.where(client_id: params[:id])
    @client_hba1c_target = Hba1cTarget.where(client_id: params[:id]).last
    @client_heartrate_target = HeartrateTarget.where(client_id: params[:id]).last
    @client_glucose_target = GlucoseTarget.where(client_id: params[:id]).last
    @client_cholesterol = Cholesterol.where(client_id: params[:id]).order('activity_date ASC').limit(4)
    @client_blood_pressure = BloodPressure.where(client_id: params[:id]).order('activity_date ASC').limit(10)
    @client_weight = Weight.where(client_id: params[:id]).order('activity_date ASC').limit(10)
    @client_weight_target = WeightTarget.where(client_id: params[:id]).last
    @client_nutrition = Nutrition.where(client_id: params[:id]).order('activity_date ASC')
    @client_complaint = Complaint.where(client_id: params[:id]).order('complain_date DESC')
    @client_medication_usage = MedicationUsage.where(client_id: params[:id]).order('activity_date ASC')
  end

  private

  def client_params
    params.require(:client).permit(:photo_url, :name, :surname, :date_of_birth, :room, :institution, :blood_type)
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/hba1cs_helper.rb
module Hba1csHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/sights_helper.rb
module SightsHelper
end

app/views/clients/index.html.haml
.co-bg.container-fluid
.row
  .col-md-3
    .instelling-image
  .col-md-8
    .search
      %form
        %input{:placeholder => "Search...", :required => "", :type => "text"}
          %input{:type => "button", :value => "Search"}
  .col-md-1
    // search nog niet werked helaas
.row
  .col-md-12
    = link_to "Client toevoegen", new_client_path, class: "btn btn-primary pull-right"
.row
  - @client.each do |c|
    .col-md-6
      .client-container
        .col-md-2
          - if c.photo_url.present?
            %img{:src => "#{c.photo_url}", :width => "50px"}
          - else
            %img{:src => "http://www.sheffield.com/wp-content/uploads/2013/06/placeholder.png", :width => "50px"}

        .col-md-9
          %p.txt-clinetenoverzicht-h1
            = c.name
            = c.surname
          %p.txt-clinetenoverzicht-h2= c.date_of_birth
        .col-md-1
          = link_to "Zie", client_path(c), class: "arrow-next" 

app/views/clients/new.html.haml
= form_for @client do |f|
  .row
    %h1 Nieuwe cliënt toevoegen

    .col-md-12
      .form-group
        = f.label :photo_url, "Foto URL"
        = f.text_field :photo_url, placeholder: 'http://www.google.nl/..', class: "form-control" 
  .row
    .col-md-6
      .form-group
        = f.label :name, "Voornaam"
        = f.text_field :name, placeholder: 'Volledig voornaam', class: "form-control"
    .col-md-6
      .form-group
        = f.label :surname, "Achternaam"
        = f.text_field :surname, placeholder: 'Achternaam inclusief tussenvoegsels', class: "form-control"
  .row 
    .col-md-12
      .form-group
        = f.label :date_of_birth, "Geboortedatum"
        = f.text_field :date_of_birth, placeholder: 'DD-MM-JJJJ', class: "form-control"
  .row 
    .col-md-12
      .form-group
        = f.label :room, "Kamer"
        = f.text_field :room, placeholder: 'Kamer nummer + letter (12B, 18A, etc.)', class: "form-control"
  .row 
    .col-md-12
      .form-group
        = f.label :institution, "Instelling"
        = f.text_field :institution, placeholder: 'Instellingnaam', class: "form-control"
  .row 
    .col-md-12
      .form-group
        = f.label :blood_type, "Bloedgroep"
        = f.text_field :blood_type, placeholder: 'Soort bloedgroep type', class: "form-control"


  = f.submit "Bevestig", class: "btn btn-primary"

app/views/clients/show.html.haml
%script{:src => "https://www.amcharts.com/lib/3/amcharts.js"}
%script{:src => "https://www.amcharts.com/lib/3/serial.js"}
%script{:src => "https://www.amcharts.com/lib/3/themes/light.js"}
%script{:src => "https://www.amcharts.com/lib/3/amstock.js"}

- @warning = "#FF6851" 
- @target_success = "#76DD72" 
- @medication_usage = "#51BDE9" 

.row.nav-margin-top
  .col-md-12
    = render 'diabetes/client_forms.html.haml'

.row
  .col-md-6
    .panel.panel-default
      .panel-body
        .row
          .col-md-12
            .title
              Cliënt
            %hr
        .row
          .col-md-4
            %a.thumbnail{:href => "#"}
              %img{:alt => "#{@client.name} #{@client.surname}", :src => "#{@client.photo_url}"}
          .col-md-5
            %h4
              = @client.name
              = @client.surname
            = @client.date_of_birth
            %br
            Bloedgroep
            = @client.blood_type 
            %br
            Kamer 
            = @client.room
            %br
            Instelling 
            = @client.institution
  .col-md-6
    .panel.panel-default
      .panel-body
        .row
          .col-md-12
            .title
              Medicatie
            %hr
        = render 'diabetes/medications.html.haml'
.row
  .col-md-12
    .panel.panel-default
      .panel-body
        .row
          .col-md-6
            .title
              Glucose
          .col-md-6
            .row
              .col-md-12
                = render 'diabetes/hba1c.html.haml'
        %hr
        .row
          .col-md-12
            = render 'diabetes/glucose_chart.html.haml'
            #chartdiv{ :style => "height: 500px"}
.row
  .col-md-8
    .panel.panel-default
      .panel-body
        .row
          .col-md-12
            .title
              Logboek
            %hr
        = render 'diabetes/log_calendar.html.haml'
        #calendar

  .col-md-4
    .panel.panel-default
      .panel-body
        = render 'diabetes/complaints.html.haml'
.row
  .col-md-12
    .panel.panel-default
      .panel-body
        .row
          .col-md-4
            .title
              Bloeddruk
          .col-md-8
            .row
              .col-md-12= render 'diabetes/heartrate.html.haml'
        .row
          .col-md-12
            %hr
        = render 'diabetes/bloodpressure_chart.html.haml'
        #bloodpressure{ :style => "height: 220px"}
.row
  .col-md-6
    .panel.panel-default
      .panel-body
        .row
          .col-md-7
            .title
              Cholesterol
          .col-md-5 
            .legenda-cholesterol    
              .lengenda-HDL 
                .legenda-text
                  HDL   
              .legenda-LDL
                .legenda-text
                  LDL
              .lengenda-remnand
                .legenda-text
                  Remnand    
        .row
          .col-md-12
            %hr
        = render 'diabetes/cholesterol_chart.html.haml'
        #cholesterol_chart{ :style => "height: 300px"}
  .col-md-6
    .panel.panel-default
      .panel-body
        .row
          .col-md-12
            .title
              Gewicht
            %hr
        = render 'diabetes/weight_chart.html.haml'
        #weight_chart{ :style => "height: 300px"}