config/routes.rb
Rails.application.routes.draw do

  root 'clients#index'
  resources :clients
  resources :sights
  resources :heartrates
  resources :blood_pressures
  resources :logs
  resources :cholesterols
  resources :hba1cs
  resources :glucoses
  resources :medications
  resources :weights
  resources :weight_targets
  resources :hba1c_targets
  resources :blood_pressure_targets
  resources :heartrate_targets
  resources :cholesterol_targets
  resources :glucose_targets
  resources :nutritions
  resources :complaints
  resources :medication_usages
  

end

app/models/activity_type.rb
class ActivityType < ActiveRecord::Base
end

app/models/allergy.rb
class Allergy < ActiveRecord::Base
end

app/models/blood_pressure.rb
class BloodPressure < ActiveRecord::Base
end

app/models/cholesterol.rb
class Cholesterol < ActiveRecord::Base
end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
end

app/models/disease.rb
class Disease < ActiveRecord::Base
end

app/models/glucose.rb
class Glucose < ActiveRecord::Base
end

app/models/hba1c.rb
class Hba1c < ActiveRecord::Base
end

app/models/hba1c_target.rb
class Hba1cTarget < ActiveRecord::Base
end

app/models/heartrate.rb
class Heartrate < ActiveRecord::Base
end

app/models/institution.rb
class Institution < ActiveRecord::Base
end

app/models/length.rb
class Length < ActiveRecord::Base
end

app/models/log.rb
class Log < ActiveRecord::Base
end

app/models/medication.rb
class Medication < ActiveRecord::Base
end

app/models/nutrition.rb
class Nutrition < ActiveRecord::Base
end

app/models/sight.rb
class Sight < ActiveRecord::Base
end

app/models/weight.rb
class Weight < ActiveRecord::Base
end

app/models/weight_target.rb
class WeightTarget < ActiveRecord::Base
end

app/controllers/blood_pressures_controller.rb
class BloodPressuresController < ApplicationController
  def index
    @blood_pressure = BloodPressure.all
end

  def new
    @blood_pressure = BloodPressure.new
  end

  def create
    @blood_pressure = BloodPressure.new(blood_pressure_params)
    @blood_pressure.save
    redirect_to client_path(blood_pressure_params[:client_id])
  end

  def edit
    @blood_pressure = BloodPressure.find(params[:id])
  end

  def update
    blood_pressure = BloodPressure.find(params[:id])
    blood_pressure.update(blood_pressure_params)
    redirect_to client_path(blood_pressure_params[:client_id])
  end

  def destroy
    blood_pressure = BloodPressure.find(params[:id])
    blood_pressure.destroy
    redirect_to client_path(blood_pressure_params[:client_id])
  end

  private

  def blood_pressure_params
    params.require(:blood_pressure).permit(:client_id, :activity_date, :sys, :dia)
  end
end

app/helpers/blood_pressures_helper.rb
module BloodPressuresHelper
end

app/helpers/hba1cs_helper.rb
module Hba1csHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/blood_pressures/edit.html.haml
= render 'forms/form_blood_pressure.html.haml', blood_pressure: @blood_pressure

app/views/blood_pressures/index.html.haml
= link_to "Bloeddruk toevoegen", new_blood_pressure_path

  - @blood_pressure.each do |bp|
  %br 
  = bp.sys
  = bp.dia
  = bp.activity_date
 
  = link_to "Edit", edit_blood_pressure_path(bp)
  = link_to "Delete", blood_pressure_path(bp), method: :delete, data:{confirm: "Weet u het zeker?"}

app/views/blood_pressures/new.html.haml
= render 'forms/form_blood_pressure.html.haml', blood_pressure: @blood_pressure 

app/views/blood_pressures/show.html.haml
.row
  .col-md-6
    .row
      .col-md-6
        .bg-blood-pressure
          .row 
            .col-md-9
              %p.header-txt Hartslag
            .col-md-3
              .heart 
          .row
            .col-md-12
              .row-2-blood-pressure
                .col-md-8.col-md-offset-2
                  %p.heart-rate-past 75 
                  %p.heart-rate 85
                  %p.header-txt-bpm BPM
          .row
            .col-md-12
              %p.footer-txt Hba1c laatst gemeten op 12-04-16
      .col-md-4